apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    app: order-service
data:
  db-host: "postgres-service"
  db-port: "5432"
  db-user: "madeinworld_admin"
  db-name: "madeinworld_db"
  db-sslmode: "prefer"
  jwt-expiration-hours: "24"
  auth-service-url: "http://auth-service:8081"
  catalog-service-url: "http://catalog-service:8080"
  stock-buffer: "5"
  enable-stock-validation: "true"
  default-order-status: "Pending"
  enable-order-notifications: "false"
  log-level: "info"
  log-format: "json"
