apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    service: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: madeinworld/order-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: ORDER_PORT
          value: "8082"
        - name: GIN_MODE
          value: "release"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: db-port
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: db-user
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: db-name
        - name: DB_SSLMODE
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: db-sslmode
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-service-secret
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: order-service-secret
              key: jwt-secret
        - name: JWT_EXPIRATION_HOURS
          valueFrom:
            configMapKeyRef:
              name: order-service-config
              key: jwt-expiration-hours
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
