apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  labels:
    app: order-service
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  # To encode: echo -n "your-secret" | base64
  db-password: eW91ci1kYXRhYmFzZS1wYXNzd29yZA==  # your-database-password
  jwt-secret: eW91ci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=  # your-secret-key-change-this-in-production
---
# Example of how to create the secret using kubectl:
# kubectl create secret generic order-service-secret \
#   --from-literal=db-password=your-database-password \
#   --from-literal=jwt-secret=your-secret-key-change-this-in-production
