apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    service: order-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-nodeport
  labels:
    app: order-service
    service: order-service
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30082
    protocol: TCP
    name: http
  selector:
    app: order-service
