apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: default
  labels:
    app: auth-service
    component: secret
type: Opaque
data:
  # This will be populated by AWS Secrets Manager or manually encoded
  # To encode: echo -n "your_password" | base64
  # Base64 encoded database password from AWS Secrets Manager
  DB_PASSWORD: "TWFkZUluV29ybGRzc3MyMDA1IT8="
  # Base64 encoded JWT secret - CHANGE THIS IN PRODUCTION
  # To encode: echo -n "your-super-secret-jwt-key-change-this-in-production" | base64
  JWT_SECRET: "eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u"

---
# Alternative: Use AWS Secrets Manager with External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: madeinworld-db-password
      property: password
  - secretKey: JWT_SECRET
    remoteRef:
      key: madeinworld-jwt-secret
      property: secret
