# workers/edge-proxy/wrangler.toml
name = "madeinworld-edge-proxy"
main = "src/index.js"
compatibility_date = "2024-05-12"

# CORRECTED: No angle brackets
account_id = "3ffb93116c8d5ab05b5d0f5482296954"

# CORRECTED: Route syntax
routes = [
  { pattern = "device-api.expomadeinworld.com/*", zone_name = "expomadeinworld.com" }
]

[vars]

AUTH_SERVICE_URL    = "cmcqqznz9g.eu-central-1.awsapprunner.com"
CATALOG_SERVICE_URL = "a2uxqsmufm.eu-central-1.awsapprunner.com"
ORDER_SERVICE_URL   = "nmnr8p57tp.eu-central-1.awsapprunner.com"
USER_SERVICE_URL    = "u4spyijvtc.eu-central-1.awsapprunner.com"