apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: default
  labels:
    app: catalog-service
    component: config
data:
  DB_HOST: "madeinworld-dev-db.c52e4w2moi2w.eu-central-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "madeinworld_admin"
  DB_NAME: "madeinworld_db"
  DB_SSLMODE: "require"
  PORT: "8080"
  GIN_MODE: "release"
