apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: default
  labels:
    app: catalog-service
    component: secret
type: Opaque
data:
  # This will be populated by AWS Secrets Manager or manually encoded
  # To encode: echo -n "your_password" | base64
  # Base64 encoded database password from AWS Secrets Manager
  DB_PASSWORD: "TWFkZUluV29ybGRzc3MyMDA1IT8="

---
# Alternative: Use AWS Secrets Manager with External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: catalog-service-db-password
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: catalog-service-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: madeinworld-db-password
      property: password
