# .github/workflows/deploy-app-runner.yml

name: Deploy Services to App Runner

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, catalog-service, order-service, user-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: madeinworld/${{ matrix.service }}
          IMAGE_TAG: latest
        run: |
          set -e
          BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "Building image for $ECR_REPOSITORY with GIT_SHA=$GITHUB_SHA BUILD_TIME=$BUILD_TIME"
          docker build \
            --build-arg GIT_SHA=$GITHUB_SHA \
            --build-arg BUILD_TIME=$BUILD_TIME \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./backend/${{ matrix.service }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Ensure App Runner deployment
        env:
          SERVICE_NAME: madeinworld-${{ matrix.service }}-dev
        run: |
          set -e
          ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='$SERVICE_NAME'].ServiceArn | [0]" --output text)
          if [ -z "$ARN" ] || [ "$ARN" = "None" ]; then
            echo "No App Runner service found for $SERVICE_NAME" >&2
            exit 1
          fi
          echo "Service ARN: $ARN"

          # Trigger deployment explicitly to pick latest:latest image
          set +e
          aws apprunner start-deployment --service-arn "$ARN"
          RC=$?
          set -e
          if [ $RC -ne 0 ]; then
            echo "start-deployment not allowed or failed (likely ongoing or auto-deploy enabled); continuing"
          fi

          echo "Waiting for deployment to complete (will poll up to 15 minutes)"
          for i in {1..90}; do
            STATUS=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.Status" --output text)
            DEP_STATUS=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.Deployments[0].Status" --output text 2>/dev/null || echo "unknown")
            IMG_ID=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.SourceConfiguration.ImageRepository.ImageIdentifier" --output text)
            echo "[$i] Status: $STATUS | Deployment: $DEP_STATUS | Image: $IMG_ID"
            if [ "$STATUS" = "RUNNING" ] && [ "$DEP_STATUS" = "SUCCEEDED" ]; then
              break
            fi
            sleep 10
          done

          echo "Final service description:"
          aws apprunner describe-service --service-arn "$ARN"
