# .github/workflows/deploy-app-runner.yml

name: Deploy Services to App Runner

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, catalog-service, order-service, user-service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: madeinworld/${{ matrix.service }}
          LATEST_TAG: latest
          SHA_TAG: ${{ github.sha }}
        run: |
          set -e
          BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "Building image for $ECR_REPOSITORY with GIT_SHA=$GITHUB_SHA BUILD_TIME=$BUILD_TIME"
          docker build \
            --build-arg GIT_SHA=$GITHUB_SHA \
            --build-arg BUILD_TIME=$BUILD_TIME \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG \
            ./backend/${{ matrix.service }}
          echo "Pushing tags: $LATEST_TAG and $SHA_TAG"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$LATEST_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG
          echo "Resolving ECR digest for $SHA_TAG"
          DIGEST=$(aws ecr describe-images --repository-name "$ECR_REPOSITORY" --image-ids imageTag=$SHA_TAG --query 'imageDetails[0].imageDigest' --output text)
          echo "Image digest: $DIGEST"
          echo "ecr_image_sha_digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Ensure App Runner deployment
        env:
          SERVICE_NAME: madeinworld-${{ matrix.service }}-dev
        run: |
          set -e
          ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='$SERVICE_NAME'].ServiceArn | [0]" --output text)
          if [ -z "$ARN" ] || [ "$ARN" = "None" ]; then
            echo "No App Runner service found for $SERVICE_NAME" >&2
            exit 1
          fi
          echo "Service ARN: $ARN"

          # 1) Wait until service is RUNNING before attempting to start a deployment
          echo "Waiting for service to be RUNNING (up to 10 minutes)"
          for i in {1..60}; do
            STATUS=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.Status" --output text)
            echo "[pre-$i] Status: $STATUS"
            if [ "$STATUS" = "RUNNING" ]; then
              break
            fi
            sleep 10
          done

          STATUS=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.Status" --output text)
          if [ "$STATUS" != "RUNNING" ]; then
            echo "Service did not reach RUNNING status; continuing without manual start-deployment"
          else
            AUTO=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.SourceConfiguration.AutoDeploymentsEnabled" --output text)
            if [ "$AUTO" = "True" ]; then
              echo "Auto-deployments enabled; skipping manual start-deployment"
            else
              echo "Service is RUNNING; attempting to start-deployment"

      - name: Update App Runner image to commit SHA tag
        env:
          SERVICE_NAME: madeinworld-${{ matrix.service }}-dev
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: madeinworld/${{ matrix.service }}
          SHA_TAG: ${{ github.sha }}
        run: |
          set -e
          ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='$SERVICE_NAME'].ServiceArn | [0]" --output text)
          if [ -z "$ARN" ] || [ "$ARN" = "None" ]; then
            echo "No App Runner service found for $SERVICE_NAME" >&2
            exit 1
          fi
          NEW_IMAGE="$ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG"
          echo "Updating service $SERVICE_NAME to image: $NEW_IMAGE"
          aws apprunner update-service \
            --service-arn "$ARN" \
            --source-configuration "{\"ImageRepository\":{\"ImageIdentifier\":\"$NEW_IMAGE\",\"ImageRepositoryType\":\"ECR\",\"ImageConfiguration\":{\"Port\":\"8081\"}},\"AutoDeploymentsEnabled\":true}"
          echo "Triggered update-service to SHA-tagged image"

              echo "Manual start-deployment skipped in this workflow"
            fi
          fi

          # 2) Poll for deployment progress; if none appears but service is RUNNING, exit successfully
          echo "Waiting for deployment to complete (will poll up to 15 minutes)"
          running_no_dep_count=0
          for i in {1..90}; do
            STATUS=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.Status" --output text)
            DEP_STATUS=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.Deployments[0].Status" --output text 2>/dev/null || echo "None")
            IMG_ID=$(aws apprunner describe-service --service-arn "$ARN" --query "Service.SourceConfiguration.ImageRepository.ImageIdentifier" --output text)
            echo "[$i] Status: $STATUS | Deployment: $DEP_STATUS | Image: $IMG_ID"

            if [ "$STATUS" = "RUNNING" ] && [ "$DEP_STATUS" = "SUCCEEDED" ]; then
              echo "Deployment SUCCEEDED"
              break
            fi

            if [ "$STATUS" = "RUNNING" ] && [ "$DEP_STATUS" = "None" ]; then
              running_no_dep_count=$((running_no_dep_count+1))
              # If RUNNING with no deployment observed for ~2 minutes, proceed
              if [ $running_no_dep_count -ge 12 ]; then
                echo "Service RUNNING with no active deployment detected; proceeding"
                break
              fi
            fi

            sleep 10
          done

          echo "Final service description:"
          aws apprunner describe-service --service-arn "$ARN"
